name: Python Django

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
          POSTGRES_DB: bookstore_dev_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U bookstore_dev -d bookstore_dev_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: "supersecretkey123"
      DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
      SQL_ENGINE: "django.db.backends.postgresql"
      SQL_DATABASE: "bookstore_dev_db"
      SQL_USER: "bookstore_dev"
      SQL_PASSWORD: "bookstore_dev"
      SQL_HOST: "127.0.0.1"
      SQL_PORT: "5432"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Poetry
        run: python -m pip install --upgrade pip poetry

      - name: Install dependencies
        run: poetry install

      - name: Wait for Postgres
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U bookstore_dev; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run Django Migrations
        run: poetry run python manage.py migrate

      - name: Run Tests
        run: poetry run python manage.py test
